= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2021/22
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:** Muhammad Fakhruddin

**Gruppe:** swt21w20

== Was habe ich gelernt / was habe ich nicht gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden
Übung macht den Meister, also durch die wöchentlichen Abgabetermine muss ich jede Woche am Ball bleiben und ich habe das Gefühl, dass ich jetzt besser programmieren bzw. Lösungen googeln kann.

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?
Kommunikation ist alles. Ohne gute Kommunikation können wir nicht gut zusammenarbeiten. Wir haben wöchentlich ein bis zwei Gruppenmeeting (außer das Team-Treffen mit dem Tutor), um die Aufteilung der Aufgaben für die Woche und den aktuellen Fortschritt zu besprechen; in dieser Sitzung können wir uns auch gegenseitig bei Problemen helfen.

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?
Auf jeden Fall wird UserAccount in unserer Anwendung sehr nützlich sein, um die Datenbank der Benutzer zu verwalten. Für die anderen Feature wäre es vielleicht hilfreich zum Verstehen, wenn es nicht nur Dokumentationen, sondern auch Beispiel-Code gäbe, also wie benutzt man oder wie soll man den Code schreiben, um die Feature anzuwenden.

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.
Ich würde vorschlagen, die Gruppe bezuglich der Note des Klausurs aufzuteilen (ähnlich wie beim RoboLab), so dass die Fähigkeiten der einzelnen Gruppen ausgewogen/gleich verteilt sind.

== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?
Die Tutoren sind sehr toll und sehr sehr hilfsbereit, und meiner Meinung nach ist der Lehrraum besonders gut. Das Problem war, dass es nur in einem Termin angeboten wurde, vielleicht wäre es besser, wenn es in mehreren Terminen angeboten würde.
