= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2021/22
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von: Jorinde Wellmer**

**Gruppe: 20**

== Was habe ich gelernt / was habe ich nicht gelernt?
Während des Praktikums habe ich meine Java- und Programmierkentnisse deutlich verbessert.
Außerdem war im Lernreaum eine sehr gute Betreuung. Vorallem mit css und html hatte ich mich vorher gar nicht
beschäftigt. Allerdings finde bin ich mir beim Testschreiben oft noch unsicher und manchmal ist es
durch das mocken sehr kompliziert gewesen einfache Mechanismen zu überprüfen.
Am Anfang war es schwierig Salespoint, Spring und Thymeleaf alles auf einmal zu verstehen, da das soviel Neues war.
Allerdings hat da vor Allem die Videoshop-Aufgabe sehr geholfen.
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
Die Zusammenarbeit im Team war teilweise schwierig, da man oft unter Zeitdruck war und dann nicht mehr genug Zeit hatte,
um sich gegenseitig zu helfen. Teilweise war die Kommunikation auch schwierig und Aufgaben wurden nicht gemacht. Außerdem war das Programierniveau
teilweise sehr unterschiedlich. Manchmal hatte ich auch das Gefühl man hätte bestimmte Sachen besser besprechen können, wenn man sich
nicht nur online getroffen hätte und die Barriere nach Hilfe zu fragen oder Probleme zusammen zu besprechen wäre niedriger gewesen.
Beim nächsten Mal wäre es gut die Aufgaben besser zu verteilen, damit die Arbeitslast mehr verteilt ist und sich öfter zu treffen, gerade auch damit
sich besser an Deadlines gehalten wird.
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
Salespoint war sehr praktisch, da man sich daran "entlanghangen" konnte auch in Hinsicht darauf,
was für Klassen man alles braucht. Außerdem gab es dadurch viele Methoden, die man nicht mehr selber schreiben musste.
Teilweise hätte die Dokumentation vielleicht ein bisschen aussagekräftiger sein können.
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
Da die Deadlines immer am Montag waren, wäre für mich ein Lernraum am Ende der Woche praktischer gewesen,
da man in den Konsultationen oft schon einen neuen Lösungsansatz besprochen hat, den man dann am Anfang der Woche dann ausprobiert hat
und dann erst nachdem man unterschiedliche Ansätze ausprobiert hat, auf Probleme gestoßen ist, die man nicht unbedingt alleine lösen konnte.
Insgesamt war das Praktikum sehr stressig und zeitaufwendig.
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.

== Feedback für den Tutor
Die Betreuung durch den Tutor war sehr gut. Gerade dadurch, dass am Anfang zwei Leute abgesprungen sind,
war es gut, dass Teile der Aufgabe gestrichen wurden. Außerdem war er immer sehr kulant bei uns,
auch wenn Aufgaben nur mäßig erfüllt wurden. Außerdem konnte man immer Fragen stellen und insgesamt waren die
wöchentlichen Treffen immer sehr hilfreich um Struktur zu geben und einen Überblick zu behalten.
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?

== Sonstiges und Anmerkungen

// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
