= Protokoll Gruppe 20

Treffen am 17.01.2022

Ort:      BigBlueButton +
Beginn:   14:50 Uhr +
Ende:     16:50 Uhr

__Schriftführer:__Jesse 

*Nächstes Treffen:* +
24.01.2022, 14:50 Uhr, BigBlueButton

__Teilnehmer:__

- Alex
- Hanif
- Jesse
- Jorinde

== Bemerkungen

Der CI-Build ist aufgrund von Tests fehlgeschlagen, dies wurde jedoch während des Meetings behoben. +
Die Selbsteinschätzung wurde im Meeting durchgeführt, kann sich aber noch stellenweise ändern. +
Der Termin für die Prüfung ist der 03.02.2022 um 9.20 Uhr in einem BigBlueButton-Raum. +
Der Ablauf der Vorstellung bei der Prüfung wurde nochmal angesprochen. + 
Die Gruppe wurde auf die Umfrage zum Praktikum in GitHub hingewiesen, die bis zum 04.02.2022 auszufüllen ist.

== Retrospektive des letzten Sprints
*Issue referenziert die Issue ID von GitHub*

[option="headers"]
|===
|Issue |Aufgabe |Status 
|15     |Kundentests, abbrechen Button    |closed
|17   |backen der Pizza     |closed
|===


== Aktueller Stand

Probleme: +
- Pizzen werden teilweise aus der Warteliste gelöscht, wenn eine gebacken wird. +
- Bestellungen müssen korrekt abgeschlossen werden können. +
- Test-Coverage ist noch nicht gut.

== Planung des nächsten Sprints

Die Anwendung muss bis zum 23.01.2022 fertig sein. +
Somit sollen noch die verbliebenen Probleme in der Anwendung beseitigt werden. +
Die Developer-Documentation ist möglichst zu aktualisieren. +
Antworten für die Umfrage sollen bis nächste Woche vorbereitet werden. +



