= Protokoll Gruppe 20

Treffen am 13.12.2021

Ort:      BigBlueButton +
Beginn:   14:50 Uhr +
Ende:     16:25 Uhr

__Schriftführer:__Jesse 

*Nächstes Treffen:* +
20.12.2021, 14:50 Uhr, BigBlueButton

__Teilnehmer:__

- Alex
- Hanif
- Jesse
- Jorinde

== Bemerkungen

Vorbereitungen aufs Cross-Testing, d.h. derzeitigen ausführbaren Stand als .jar Datei packen. Diese wird Gruppe 19 gegeben, im Gegenzug erhalten wir ihr Programm.
Dieses soll getestet werden um zu überprüfen ob alles funktioniert, ggf Probleme notiert werden.
Es gab in unserem Fall einige Probleme beim Erstellen der .jar Datei, daher wurde nochmal Hilfestellung im Meeting gegeben. 
Einige Funktionen waren noch nicht vorhanden, sodass die Frist auf den 14.12. verschoben wurde, um folgendes noch nachzuimplementieren: +
- Bestellungen je nach Lieferung/Abholung in die zugehörige Bestellungsliste sortieren +
- Kunde bei Verifizierung nicht neu erstellen +
- Warenkorb leeren +
Außerdem sollen Lieferzeit, Bäcker und Zahlungsmethode noch zu den Muss-Kriterien hinzugefügt werden.

== Retrospektive des letzten Sprints
*Issue referenziert die Issue ID von GitHub*

[option="headers"]
|===
|Issue |Aufgabe |Status |Bemerkung
|13     |Code smells und bugs entfernen       |closed      |vorerst behoben, muss später evtl nochmal überprüft werden
|14 |Tests |closed |Test coverage >40%, muss aber noch höher werden
|===


== Aktueller Stand
Es fehlen leider noch einzelne Muss-Kriterien, wie die Berechnung der Lieferzeit, eine Seite für den Bäcker zum Pizza backen und die Frage nach einer Zahlungsmethode.
Außerdem einzelne Funktionen (siehe Bemerkungen).
Das Pflichtenheft wurde in einigen Bereichen aktualisiert, insbesondere die Klassendiagramme. Im Testplan wurden einzelne Testfälle hinzugefügt.

== Planung des nächsten Sprints
*Issue referenziert die Issue ID von GitHub*

In der kommenden Woche steht das Cross-Testing im Vordergrund, wobei jeder bestimmte Bereiche des Programms testen soll.
Nebenbei sollten trotzdem Fortschritte am eigenen Programm gemacht werden, beispielsweise mehr Tests und Implementierung noch fehlender Bestandteile.

