= Protokoll Gruppe 20

Treffen am 17.01.2022

Ort:      BigBlueButton +
Beginn:   14:50 Uhr +
Ende:     16:15 Uhr

__Schriftführer:__ Jesse 

*Nächstes Treffen:* +
17.01.2022, 14:50 Uhr, BigBlueButton

__Teilnehmer:__

- Alex
- Hanif
- Jesse
- Jorinde

== Bemerkungen

Nach der Woche soll das Programm möglichst vorstellbereit sein, um danach noch Entwicklerdokumentation und Testfälle bearbeiten zu können.

== Retrospektive des letzten Sprints

Die restlichen Muss-Kriterien wurden implementiert, allerdings gibt es noch Probleme beim Backvorgang und dem Bestellungsabschluss. +
Javadoc wurde teilweise implementiert. +
Die Anwendung wurde verschönert und die Tabellenstrukturen für die Übersichtlichkeit angezeigt. +
Es wurden Tests für das Kunden-Package geschrieben.

== Aktueller Stand

Es fehlt noch stellenweise Javadoc. +
Das Backen der Pizzen geschieht nicht im Hintergrund, sodass die Anwendung 5 Minuten lädt, wenn eine Pizza in den Ofen geschoben wird. +
Die Anwendung wurde verschönert/übersichtlicher gemacht.

== Planung des nächsten Sprints

[option="headers"]
|===
|Issue |Aufgabe |Status |Bemerkung
|15    |Kundentests       |offen     |Alex
|16   |Bezahlung |offen |Jorinde
|17   |backen der Pizza |offen |Hanif
|18   |PizzaListe anpassen |offen |Jesse
|===

Der Backvorgang soll gefixt werden.
Die Punkte im Cross-Testing Report sollen ausgebessert werden. +
Im Bestellungsbereich soll ein zurück-Button hinzugefügt werden, um sie Bestellung abzubrechen und auf die Startseite zurückkehren zu können. +
Weitere Tests sollen geschrieben werden, insbesondere für das Backen und um eine ausreichende Test-Coverage zu haben.

