Treffen am 01.11.2021

Ort:      BigBlueButton +
Beginn:   14:50 Uhr +
Ende:     16:25 Uhr

__Schriftführer:__ Jesse

*Nächstes Treffen:* +
08.11.2021, 14:50 Uhr, BigBlueButton

__Teilnehmer:__
//Tabellarisch oder Aufzählung, Kennzeichnung von Teilnehmern mit besonderer Rolle (z.B. Kunde)

- Alex
- Hanif
- Jesse
- Jorinde

== Bemerkungen
Eren ist aus der Gruppe ausgetreten, daher werden einige Punkte zu Kann-Kriterien: +
- Rabatt für Abholer +
- Gratisgetränk +
- Kunden bearbeiten +
- Umsatzdiagramme +
Es soll überlegt werden, wie die Fertigstellungszeit berechnet wird. +
Bestellungsübersicht für Lieferung und Abholung soll geteilt werden.

== Retrospektive des letzten Sprints
Alle bis auf Jesse fertig mit mindestens einer Videoshop-Aufgabe.
Für das Pflichtenheft hat jeder einen Teil bearbeitet sodass alle Punkte abgearbeitet wurden.

// See http://asciidoctor.org/docs/user-manual/=tables
[option="headers"]
|===
|Issue |Aufgabe |Status |Bemerkung
|…     |…       |…      |…
|===


== Aktueller Stand
Das Pflichtenheft ist größtenteils fertig aber noch stellenweise zu verbessern/verändern. +
Darauf aufbauend sollen nun Packages mit je einem Teil der Muss-Kriterien erstellt werden, wobei bereits eines bearbeitet werden soll. 

== Planung des nächsten Sprints
Aufteilung des Systems in Packages und Verteilung auf die Gruppenmitglieder.
Damit jeweils Erstellung eines Prototypen.
Vertrautmachen mit dem Salespoint Framework um mit der Arbeit am ersten Kriterium zu beginnen.

// See http://asciidoctor.org/docs/user-manual/=tables
[option="headers"]
|===
|Issue |Titel |Beschreibung |Verantwortlicher |Status
|… |… |… |… |…
|… |… |… |… |…
|===

