= Protokoll Gruppe 20

Treffen am 25.10.2021

Ort:      BigBlueButton +
Beginn:   14:50 Uhr +
Ende:     16:20 Uhr

__Schriftführer:__ Jesse

*Nächstes Treffen:* +
01.11.2021, 14:50 Uhr, BigBlueButton

__Teilnehmer:__
//Tabellarisch oder Aufzählung, Kennzeichnung von Teilnehmern mit besonderer Rolle (z.B. Kunde)

- Alex
- Hanif
- Jorinde
- Eren
- Jesse

== Bemerkungen
Besprechung des Stands der Videoshop-Aufgabe: Jorinde und Hanif haben ihre Implementierung vorgeführt. Feststellung, dass Fehlermeldung auftritt, wenn versucht wird den gleichen Namen noch einmal zu registrieren. Besprochen wer in der Woche wie oft anwesend war und Stand der UML-Diagramme besprochen (es gibt noch viel zu tun). Auf StarUML als UML-Tool geeinigt. Über die Woche aufgekommene Fragen und weitere Fragen zum Pizzashop geklärt. 
Eren ist erst später zum Treffen gekommen, weil er beim Arzt war.

== Retrospektive des letzten Sprints
*Issue referenziert die Issue ID von GitHub*
Jorinde und Hanif fertig mit Registrierung für Videoshop-Registrierungs Aufgabe.
Jesse und Alex haben auch mit der Registrierungs-Aufgabe angefangen, Frontend funktioniert aber Backend muss noch verbessert werden. Jesse will noch zu einer anderen Aufgabe wechseln, 
damit mindestens 2 verschiedene behandelt wurden und Hanif will eventuell auch noch eine zweite Aufgabe machen. 
Jorinde hat mit der Konto-Aufgabe angefangen. Eren hatte Probleme mit Eclipse, konnte noch nicht erfolgreich clonen. 

// See http://asciidoctor.org/docs/user-manual/=tables
[option="headers"]
|===
|Issue |Aufgabe |Status |Bemerkung
|…     |…       |…      |…
|===


== Aktueller Stand
einige GUI Entwürfe für das Pflichtenheft erstellt, Videoshop-Aufgaben angefangen, teilweise fertig (Registrierung Hanif & Jorinde),


== Planung des nächsten Sprints
1. Alle Gruppenmitglieder sollen die Videoshop-Aufgabe anfangen oder beenden. 
2. Das Pflichtenheft muss fertiggestellt werden (min 10 Diagramme).
3. Protokoll muss überarbeitet werden.
*Issue referenziert die Issue ID von GitHub*

// See http://asciidoctor.org/docs/user-manual/=tables
[option="headers"]
|===
|Issue |Titel |Beschreibung |Verantwortlicher |Status
|… |… |… |… |…
|… |… |… |… |…
|===
